// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: urlshortener/v1/service.proto

package urlshortenerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShortenerAPIClient is the client API for ShortenerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortenerAPIClient interface {
	// Create a shortened link from the given URL.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Resolve the shortened URL.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type shortenerAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerAPIClient(cc grpc.ClientConnInterface) ShortenerAPIClient {
	return &shortenerAPIClient{cc}
}

func (c *shortenerAPIClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/cloud.urlshortener.v1.ShortenerAPI/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerAPIClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, "/cloud.urlshortener.v1.ShortenerAPI/Resolve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerAPIServer is the server API for ShortenerAPI service.
// All implementations must embed UnimplementedShortenerAPIServer
// for forward compatibility
type ShortenerAPIServer interface {
	// Create a shortened link from the given URL.
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// Resolve the shortened URL.
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	mustEmbedUnimplementedShortenerAPIServer()
}

// UnimplementedShortenerAPIServer must be embedded to have forward compatible implementations.
type UnimplementedShortenerAPIServer struct {
}

func (UnimplementedShortenerAPIServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedShortenerAPIServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedShortenerAPIServer) mustEmbedUnimplementedShortenerAPIServer() {}

// UnsafeShortenerAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortenerAPIServer will
// result in compilation errors.
type UnsafeShortenerAPIServer interface {
	mustEmbedUnimplementedShortenerAPIServer()
}

func RegisterShortenerAPIServer(s grpc.ServiceRegistrar, srv ShortenerAPIServer) {
	s.RegisterService(&ShortenerAPI_ServiceDesc, srv)
}

func _ShortenerAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.urlshortener.v1.ShortenerAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerAPIServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenerAPI_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerAPIServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.urlshortener.v1.ShortenerAPI/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerAPIServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortenerAPI_ServiceDesc is the grpc.ServiceDesc for ShortenerAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortenerAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.urlshortener.v1.ShortenerAPI",
	HandlerType: (*ShortenerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ShortenerAPI_Create_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _ShortenerAPI_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "urlshortener/v1/service.proto",
}
